import Header from "@/components/organisms/Header";
import Providers from "@/app/providers";

import "./globals.css";
import Navbar from "@/components/organisms/Navbar";

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="en">
   <head>
    <title>IMDB</title>
   </head>
   <body>
    <Providers>
     <Header />
     <Navbar />
     {/* SearchBox */}
     {children}
    </Providers>
   </body>
  </html>
 );
}
